config/routes.rb
InventoryApp::Application.routes.draw do
  get "dashboard/index"
  resources :users
  resources :items
  resources :suppliers
  resources :tasks
  resources :storage_locations
  resources :sessions, :only => [:new, :create, :destroy]

  match "/dashboard", :to => 'dashboard#index', :via=> [:get]
  match "/signup",  :to => 'users#new', :via=> [:get]
  match "/signin",  :to => 'sessions#new', :via=> [:get]
  match "/signout", :to => 'sessions#destroy', :via=> [:get]

  root 'sessions#new'

  

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user_id
  has_many :suppliers, through: :item_suppliers
  has_many :item_suppliers
  has_many :storage_locations, through: :itemstoragelocations
  has_many :itemstoragelocations
  
  validates :name, :current_amount, :min_amount, :max_amount, :purchase_amount, :unit_name, :unit_quantity, :presence => true

end

app/models/item_supplier.rb
class ItemSupplier < ActiveRecord::Base
  belongs_to :item
  belongs_to :supplier
end

app/models/itemstoragelocation.rb
class Itemstoragelocation < ActiveRecord::Base
  belongs_to :item
  belongs_to :storage_location
end

app/models/storage_location.rb
class StorageLocation < ActiveRecord::Base
	has_many :tasks
	has_many :items, through: :itemstoragelocations
	has_many :itemstoragelocations

	validates :name, :presence => true
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
	has_many :items, through: :item_suppliers
	has_many :item_suppliers
	validates :name, :presence => true

	# attr_accessible :primary, :secondary, :name
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user_id
  belongs_to :storage_location_id

  validates :description, :presence => true

  # attr_accessible :description
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :items
	has_many :tasks

	email_regex = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i

    validates :first_name,		:presence 	=> true,
  			  :length		            => { :maximum => 50 }
    validates :last_name,		:presence 	=> true,
  			  :length		            => { :maximum => 50 }
    validates :email,		    :presence	=> true,
  			  :format		            => { :with => email_regex },
           	  :uniqueness 	            => { :case_sensitive => false }
    validates :password, 		:length			        => { :within => 6..40 }


    has_secure_password
    # attr_accessor :password
    # attr_accessible :password, :password_confirmation
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  	@user = User.find(session[:user_id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
    @item = Item.new
    @suppliers = Supplier.all
    @storage_locations = StorageLocation.all
    @user = current_user
  end

  def create
    @item = Item.new(name: params[:item][:name], current_amount: params[:item][:current_amount], unit_quantity: params[:item][:unit_quantity], unit_name: params[:item][:unit_name], min_amount: params[:item][:min_amount], max_amount: params[:item][:max_amount], notes: params[:item][:notes], purchase_amount: params[:item][:purchase_amount])
    # @item = Item.new(item_params)
    if @item.save
      @item.suppliers += [Supplier.find(params[:item][:suppliers][:id])]
      @item.storage_locations += [StorageLocation.find(params[:item][:storage_location][:id])]
      redirect_to items_path
    else
      puts @item.errors.full_messages
      redirect_to :back, :flash => { :state => 'register', :errors => @item.errors.full_messages } 
    end
  end

  def update
    puts params
    @item = Item.update(params[:id], item_params)
    redirect_to items_path
  end

  def edit
    @item = Item.find(params[:id])
    @suppliers = Supplier.all
  end

  def index
    @items = Item.all
    @suppliers = Supplier.all
    @user = current_user
  end

  def destroy
    Item.find(params[:id]).destroy
    redirect_to items_path
  end

  private
  def item_params
    params.require(:item).permit(:name, :current_amount, :min_amount, :max_amount, :purchase_amount, :unit_name, :unit_quantity, :notes)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	# render text: params
  	user = User.find_by(email: params[:session][:email]).try(:authenticate, params[:session][:password])
  	# user = User.authenticate(params[:session][:email], params[:session][:password])
	if user == false || user.nil?
		flash.now[:error] = "Invalid email/password combination."
		redirect_to new_session_path, :flash => { :error => 'Email and password don\'t match.' }
	else
		log_in user
		redirect_to users_path
	end
  end

  def destroy
  	log_out
  	redirect_to new_session_path
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  def new
        @user = current_user
        @suppliers = Supplier.all
  end

  def create
  end

  def update
  end

  def edit
  end

  def index
    deny_access unless logged_in?
    @user = User.find(session[:user_id])
    redirect_to items_path
  end

  def show
    # @items = Item.all
    @suppliers = Supplier.all
    @findsupplier = Supplier.find(params[:id])
    @items = @findsupplier.items
    # @finditem = Item.find(params[:id])
    @user = current_user
  end

  def destroy
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
  end

  def create
  end

  def update
  end

  def edit
  end

  def show
  end

  def index
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to users_url, :notice => "#{@user.first_name} Registered!"
    else
      render :new
    end
  end

  def show
    deny_access unless logged_in?
    @user = User.find(params[:id])
  end

  def dashboard
  end

  def index
    deny_access unless logged_in?
    # @users = User.all
    @user = User.find(session[:user_id])
    redirect_to suppliers_path
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in user
		session[:user_id] = user.id
		self.current_user = user
	end

	# setter method
	def current_user= user
		@current_user = user
	end

	# getter method
	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	# NOTE: why not attr_accessor :current_user?

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session[:user_id] = nil
		self.current_user = nil
	end

	def current_user? user
		user == current_user
	end

	def deny_access
		redirect_to new_session_path, :alert => "Please log in to access this page."
	end

end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InventoryApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<link href='http://fonts.googleapis.com/css?family=Droid+Sans:400,700' rel='stylesheet' type='text/css'> 
	<link href='http://fonts.googleapis.com/css?family=Leckerli+One' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_footer.html.erb
	<div class="footer-wrapper">
		<div id="footer">
			Another Project by <a href="">MaleesaMade</a>
		</div>
	</div>

app/views/shared/_header.html.erb
	<div id="header-info">
		<div class="header-wrapper">
			<div id="header">
				<h1 id="logo">
					CafeInventory
				</h1>
			</div>
			<div id="right-header">
				<ul id="navigation">
					<li class="first"><%= link_to "Home", items_path, class: "nav-link" %></li>	
					<li><%= link_to "Contact", new_supplier_path, class: "nav-link" %></li>
					<li class="last"><%= link_to "Log Out", signout_path, class: "nav-link" %></li>
				</ul>
				<h4 id="user_name"> 
					Hi, <%= @user.first_name %>!
				</h4>
			</div>
		</div>
	</div>

app/views/shared/_leftcolumn.html.erb
		<div id="left">
			<span id="title-master" class="title">MASTER LIST</span>
			<ul class="left-nav">
				<li id="master"><%= link_to "Inventory", items_path, id: "master-text" %></li>
			</ul>
			<span id="title-stores" class="title">SUPPLIERS</span>
			<ul class="left-nav">
				<% @suppliers.each do |supplier| %>
					<li><%= link_to supplier.name, supplier_path(supplier.id) %></li>
				<% end %>
			</ul>
		</div>

app/views/shared/_regfooter.html.erb
<div id="footer-info">
	Another little project by <a href="http://www.maleesamade.com">MaleesaMade</a>.
</div>

app/views/shared/_regheader.html.erb
	<div id="header-info">
		<div class="header-wrapper">
			<div id="header">
				<h1 id="logo">
					CafeInventory
				</h1>
			</div>
			<div id="right-header">
				<h4 id="user_name"> 
				</h4>
			</div>
		</div>
	</div>