config/routes.rb
InventoryApp::Application.routes.draw do
  get "dashboard/index"
  resources :users
  resources :items
  resources :suppliers
  resources :tasks
  resources :storage_locations
  resources :sessions, :only => [:new, :create, :destroy]

  match "/dashboard", :to => 'dashboard#index', :via=> [:get]
  match "/signup",  :to => 'users#new', :via=> [:get]
  match "/signin",  :to => 'sessions#new', :via=> [:get]
  match "/signout", :to => 'sessions#destroy', :via=> [:get]

  root 'sessions#new'

  

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user_id
  has_many :suppliers, through: :item_suppliers
  has_many :item_suppliers
  has_many :storage_locations, through: :itemstoragelocations
  has_many :itemstoragelocations
  
  validates :name, :current_amount, :min_amount, :max_amount, :purchase_amount, :unit_name, :unit_quantity, :presence => true

end

app/models/item_supplier.rb
class ItemSupplier < ActiveRecord::Base
  belongs_to :item
  belongs_to :supplier
end

app/models/itemstoragelocation.rb
class Itemstoragelocation < ActiveRecord::Base
  belongs_to :item
  belongs_to :storage_location
end

app/models/storage_location.rb
class StorageLocation < ActiveRecord::Base
	has_many :tasks
	has_many :items, through: :itemstoragelocations
	has_many :itemstoragelocations

	validates :name, :presence => true
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
	has_many :items, through: :item_suppliers
	has_many :item_suppliers
	validates :name, :presence => true

	# attr_accessible :primary, :secondary, :name
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user_id
  belongs_to :storage_location_id

  validates :description, :presence => true

  # attr_accessible :description
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :items
	has_many :tasks

	email_regex = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i

    validates :first_name,		:presence 	=> true,
  			  :length		            => { :maximum => 50 }
    validates :last_name,		:presence 	=> true,
  			  :length		            => { :maximum => 50 }
    validates :email,		    :presence	=> true,
  			  :format		            => { :with => email_regex },
           	  :uniqueness 	            => { :case_sensitive => false }
    validates :password, 		:length			        => { :within => 6..40 }


    has_secure_password
    # attr_accessor :password
    # attr_accessible :password, :password_confirmation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  	@user = User.find(session[:user_id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
    @item = Item.new
    @suppliers = Supplier.all
    @storage_locations = StorageLocation.all
    @user = current_user
  end

  def create
    @item = Item.new(name: params[:item][:name], current_amount: params[:item][:current_amount], unit_quantity: params[:item][:unit_quantity], unit_name: params[:item][:unit_name], min_amount: params[:item][:min_amount], max_amount: params[:item][:max_amount], notes: params[:item][:notes], purchase_amount: params[:item][:purchase_amount])
    # @item = Item.new(item_params)
    if @item.save
      @item.suppliers += [Supplier.find(params[:item][:suppliers][:id])]
      @item.storage_locations += [StorageLocation.find(params[:item][:storage_location][:id])]
      redirect_to items_path
    else
      puts @item.errors.full_messages
      redirect_to :back, :flash => { :state => 'register', :errors => @item.errors.full_messages } 
    end
  end

  def update
    puts params
    @item = Item.update(params[:id], item_params)
    redirect_to items_path
  end

  def edit
    @item = Item.find(params[:id])
    @suppliers = Supplier.all
  end

  def index
    @items = Item.all
    @suppliers = Supplier.all
    @user = current_user
  end

  def destroy
    Item.find(params[:id]).destroy
    redirect_to items_path
  end

  private
  def item_params
    params.require(:item).permit(:name, :current_amount, :min_amount, :max_amount, :purchase_amount, :unit_name, :unit_quantity, :notes)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	# render text: params
  	user = User.find_by(email: params[:session][:email]).try(:authenticate, params[:session][:password])
  	# user = User.authenticate(params[:session][:email], params[:session][:password])
	if user == false || user.nil?
		flash.now[:error] = "Invalid email/password combination."
		redirect_to new_session_path, :flash => { :error => 'Email and password don\'t match.' }
	else
		log_in user
		redirect_to users_path
	end
  end

  def destroy
  	log_out
  	redirect_to new_session_path
  end
end

app/controllers/storage_locations_controller.rb
class StorageLocationsController < ApplicationController
  def new
  end

  def create
  end

  def update
  end

  def edit
  end

  def index
  end

  def destroy
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  def new
        @user = current_user
        @suppliers = Supplier.all
  end

  def create
  end

  def update
  end

  def edit
  end

  def index
    deny_access unless logged_in?
    @user = User.find(session[:user_id])
    redirect_to items_path
  end

  def show
    # @items = Item.all
    @suppliers = Supplier.all
    @findsupplier = Supplier.find(params[:id])
    @items = @findsupplier.items
    # @finditem = Item.find(params[:id])
    @user = current_user
  end

  def destroy
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
  end

  def create
  end

  def update
  end

  def edit
  end

  def show
  end

  def index
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to users_url, :notice => "#{@user.first_name} Registered!"
    else
      render :new
    end
  end

  def show
    deny_access unless logged_in?
    @user = User.find(params[:id])
  end

  def dashboard
  end

  def index
    deny_access unless logged_in?
    # @users = User.all
    @user = User.find(session[:user_id])
    redirect_to suppliers_path
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in user
		session[:user_id] = user.id
		self.current_user = user
	end

	# setter method
	def current_user= user
		@current_user = user
	end

	# getter method
	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	# NOTE: why not attr_accessor :current_user?

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session[:user_id] = nil
		self.current_user = nil
	end

	def current_user? user
		user == current_user
	end

	def deny_access
		redirect_to new_session_path, :alert => "Please log in to access this page."
	end

end

app/helpers/storage_locations_helper.rb
module StorageLocationsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/index.html.erb
<div class="wrapper">
	<%= render "shared/header" %>
	<div class="content-wrapper">	
		<div id="content">
			<div id="sort">
				<h3>Inventory</h3>
				<div class="button_right">
					<%= link_to "Add Item", new_item_path, class: "button_save" %>

				</div>
				<div id="row">
					<p>Sort By: </p>
					<a href="" class="sorted" id="current_sort">Items A-Z</a>
					<a href="" class="sorted">Cafe Location</a>
					<a href="" class="sorted">Supplier</a>
				</div>
			</div>
			<div id="product-table">
				<table>
					<div id="top_row">					
					<tr>
						<th>Item</th>
						<th>Current Quantity</th>
						<th>Units</th>
						<th>Cafe Location</th>
						<th>Supplier</th>
						<th>Notes</th>
					</tr>
					</div>
					<% @items.each do |item| %>
						<tr>
							<td><%= item.name %></td>
							<td>
								<%= simple_form_for item do |f| %>
								<!-- <input id="quantity" type="text" value="<%= item.current_amount %>"> -->
									<%= f.input :current_amount, :label=>false, :value=> item.current_amount , :input_html => {:class=> "item-amount"} %>
								<% end %>
							</td>
							<td><%= item.unit_quantity %> <%= item.unit_name %></td>
							<td>
								<% item.storage_locations.each do |location| %>
									<%= location.name %>
								<% end %>
							</td>
							<td>
								<% item.suppliers.each do |supplier| %>
									<%= supplier.name %>
								<% end %>
							</td>
							<td><%= item.notes %></td>
						</tr>
					<% end %>
				</table>	
			</div>
		</div>
		<%= render "shared/leftcolumn" %>
	</div>
	<!--container-->
	<%= render "shared/footer" %>
	<!--footer-->
</div>

<script type="text/javascript">
	$(document).ready(function(){
		$(document).on("change", ".item-amount", function(){
			$($($(this).parent()).parent()).submit();
		})
	});
</script>

app/views/items/new.html.erb
<div class="wrapper">
	<%= render "shared/header" %>
	<div class="content-wrapper">
			<div id="content">
				<div id="sort">					
					<h3>Add New Item</h3>
					<div class="button_right">
					</div>
				</div>
				<div id="product-table">
						<%= simple_form_for @item, :html => {:class => 'pull-left'} do |f| %>
						  <%= f.input :name, label: 'Name of item', placeholder: 'ie: "Avocados"' %>
						  <%= f.input :current_amount, label: 'Current Amount', placeholder: '?' %>
						  <%= f.input :unit_quantity, label: 'Unit Quantity', placeholder: '1' %>
						  <%= f.input :unit_name, label: 'Unit Type', placeholder: 'LB' %>
						  <%= f.input :min_amount, label: 'Min Amount', placeholder: 'threshold' %>
						  <%= f.input :max_amount, label: 'Max Amount', placeholder: 'full house' %>
						  <%= f.input :purchase_amount, label: 'Purchase Amount', placeholder: 'xx' %>
						  <%= f.input :notes, label: 'Notes' %>
						  <%= f.simple_fields_for :suppliers do |s_form| %>
						  <%= s_form.input :id, :collection => @suppliers, :label => "Suppliers" %>
						  <% end %>
						  <%= f.simple_fields_for :storage_location do |s_form| %>
						  <%= s_form.input :id, :collection => @storage_locations, :label => "Storage Location" %>
						  <% end %>
						  <%= f.button :submit, :class => 'button_save' %>
						<% end %>
				</div>
			</div>
		<%= render "shared/leftcolumn" %>
	</div>
<%= render "shared/footer" %>
</div>	

app/views/storage_locations/create.html.erb
<h1>StorageLocations#create</h1>
<p>Find me in app/views/storage_locations/create.html.erb</p>

app/views/storage_locations/destroy.html.erb
<h1>StorageLocations#destroy</h1>
<p>Find me in app/views/storage_locations/destroy.html.erb</p>

app/views/storage_locations/edit.html.erb
<h1>StorageLocations#edit</h1>
<p>Find me in app/views/storage_locations/edit.html.erb</p>

app/views/storage_locations/index.html.erb
<h1>StorageLocations#index</h1>
<p>Find me in app/views/storage_locations/index.html.erb</p>

app/views/storage_locations/new.html.erb
<h1>StorageLocations#new</h1>
<p>Find me in app/views/storage_locations/new.html.erb</p>

app/views/storage_locations/update.html.erb
<h1>StorageLocations#update</h1>
<p>Find me in app/views/storage_locations/update.html.erb</p>

app/views/suppliers/create.html.erb
<h1>Suppliers#create</h1>
<p>Find me in app/views/suppliers/create.html.erb</p>

app/views/suppliers/edit.html.erb
<h1>Suppliers#edit</h1>
<p>Find me in app/views/suppliers/edit.html.erb</p>

app/views/suppliers/index.html.erb
<h1>Suppliers#index</h1>
<p>Find me in app/views/suppliers/index.html.erb</p>

app/views/suppliers/new.html.erb
<div class="wrapper">
	<%= render "shared/header" %>
	<div class="content-wrapper">
			<div id="content">
				<div id="sort">					
					<h3>Contact</h3>
					<div class="button_right">
					</div>
					
				</div>
				<div id="product-table">
					<%= mail_to "maleesapollock@gmail.com" %>
				</div>
			</div>
		<%= render "shared/leftcolumn" %>
	</div>
<%= render "shared/footer" %>
</div>

app/views/suppliers/show.html.erb
<div class="wrapper">
	<%= render "shared/header" %>
	<div class="content-wrapper">
			<div id="content">
				<div id="sort">					
					<h3><%= @findsupplier[:name] %></h3>
					<div class="button_right">
						<%= link_to "Add Item", new_item_path, class: "button_save" %>
					</div>
					<div id="row">
						<p>Sort By: </p>
						<a href="" class="sorted" id="current_sort">Items A-Z</a>
						<a href="" class="sorted">Cafe Location</a>
						<a href="" class="sorted">Supplier</a>
					</div>
				</div>
				<div id="product-table">
					<table>
						<div id="top_row">					
						<tr>
							<th></th>
							<th>Item</th>
							<th>Quantity Needed</th>
							<th>Units</th>
							<th>Notes</th>
						</tr>
						</div>
<!-- 							if @findsupplier[:name] = @finditem[] -->
							<% @items.each do |item| %>
								<tr>
									<td>									
										<%= simple_form_for item do |f| %>
											<%= f.input :name, :as => :boolean, :label=>false %>
										<% end %>
									</td>
									<td><%= item.name %></td>
									<td><%= item.purchase_amount %></td>
									<td><%= item.unit_quantity %> <%= item.unit_name %></td>
									<td><%= item.notes %></td>
								</tr>
							<% end %>
					</table>	
				</div>
			</div>
		<%= render "shared/leftcolumn" %>
	</div>
<%= render "shared/footer" %>
</div>

app/views/suppliers/update.html.erb
<h1>Suppliers#update</h1>
<p>Find me in app/views/suppliers/update.html.erb</p>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<p>Find me in app/views/tasks/edit.html.erb</p>

app/views/tasks/index.html.erb
<h1>Tasks#index</h1>
<p>Find me in app/views/tasks/index.html.erb</p>

app/views/tasks/new.html.erb
<h1>Tasks#new</h1>
<p>Find me in app/views/tasks/new.html.erb</p>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>
<h1>Hi <%= @user.first_name.upcase %>!</h1>
<%= link_to 'Logout', signout_path, :method => :get %>

app/views/users/new.html.erb
<div class="wrapper">
	<%= render "shared/regheader" %>
	<div class="content-wrapper">
			<div class="banner">
				<%= simple_form_for(@user) do |f| %>
				  <%= f.input :first_name %>
				  <%= f.input :last_name %>
				  <%= f.input :email %>
				  <%= f.input :password %>
				  <%= f.input :password_confirmation %>
				  <%= f.button :submit, class: "button_save", id: "createuserbutton" %>
				<% end %>
			<h5><%= link_to "Already a user?", new_session_path %></h5>
			</div>
	</div>
<%= render "shared/regfooter" %>
</div>
 

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>